In [27]:
import pandas as pd
apartment_table = pd.read_csv("apartment.csv")
apartment_table.head()

,Unnamed: 0,Rooms,Residential complex,City,District,Address,Apartment area,Price,Price/m2,Year,Commissioned/not commissioned,Housing class,Material
0,0,4-комнатной,Anar,г. Астана,,ул. Орынбор 13,127 м²,75 000 000,590 551,2023,Сдан,Комфорт,Кирпичные
1,1,2-комнатной,Garden View,г. Астана,,ул. Бухар жырау 26 стр,47.68 м²,43 950 000,921 770,2024,Не сдан,Бизнес+,Монолитные
2,2,3-комнатной,Самрук Towers,г. Астана,,ул. Кайыма Мухамедханова 17,86 м²,38 000 000,441 860,2018,Сдан,Эконом,Монолитные
3,3,1-комнатной,GreenLine.Headliner,г. Астана,,ул. Толе би 50,45 м²,37 500 000,833 333,2022,Не сдан,Бизнес,
4,4,2-комнатной,GreenLine.Flora,г. Астана,,ул. Е 900 4,50.1 м²,35 500 000,708 583,2024,Не сдан,Бизнес,Монолитные

In [29]:
apartment_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     900 non-null    int64
 1   Rooms                          900 non-null    object
 2   Residential complex            898 non-null    object
 3   City                           900 non-null    object
 4   District                       900 non-null    object
 5   Address                        900 non-null    object
 6   Apartment area                 900 non-null    object
 7   Price                          900 non-null    object
 8   Price/m2                       900 non-null    object
 9   Year                           900 non-null    int64
 10  Commissioned/not commissioned  900 non-null    object
 11  Housing class                  900 non-null    object
 12  Material                       900 non-null    object
dtypes: int64(2), object(11)
memory usage: 91.5+ KB

In [31]:
import numpy as np
apartment_table.replace(r'^\s*$', np.nan, regex=True, inplace=True)

In [19]:
apartment_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     900 non-null    int64
 1   Rooms                          900 non-null    object
 2   Residential complex            898 non-null    object
 3   City                           900 non-null    object
 4   District                       626 non-null    object
 5   Address                        274 non-null    object
 6   Apartment area                 900 non-null    object
 7   Price                          900 non-null    object
 8   Price/m2                       900 non-null    object
 9   Year                           900 non-null    int64
 10  Commissioned/not commissioned  900 non-null    object
 11  Housing class                  880 non-null    object
 12  Material                       272 non-null    object
dtypes: int64(2), object(11)
memory usage: 91.5+ KB

In [121]:
apartment_table['Address'].unique()

array(['ул. Орынбор 13', 'ул. Бухар жырау 26 стр',
       'ул. Кайыма Мухамедханова 17', 'ул. Толе би 50', 'ул. Е 900 4',
       'Unknown', 'ул. Бухар жырау 31', 'ул. Фаризы Онгарсыновой 6/2',
       'ул. Хусейн бен Талал (31-я) 39/1', 'ул. Т. Рыскулова 16',
       'ул. Толе би 18', 'ул. Кабанбай батыра 6', 'ул. Бухар жырау 33',
       'ул. Е-509, 7'], dtype=object)

In [122]:
apartment_table[apartment_table['Address'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, Rooms, Residential complex, City, District, Address, Apartment area, Price, Price/m2, Year, Commissioned/not commissioned, Housing class, Material]
Index: []

In [123]:
apartment_table['Address'] = apartment_table.apply(
    lambda row: 'Unknown' if pd.notna(row['District']) and 'ул.' in row['District'] and pd.isna(row['Address']) else row['Address'],
    axis=1
)
print(apartment_table['Address'].isna().sum())

0

In [124]:
apartment_table[apartment_table['Address'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, Rooms, Residential complex, City, District, Address, Apartment area, Price, Price/m2, Year, Commissioned/not commissioned, Housing class, Material]
Index: []

In [125]:
apartment_table[apartment_table['District'].str.contains('район', na=False)]['District'].unique()

array(['Есильский район', 'Нура район', 'Есильский район 18',
       'Есильский район 15'], dtype=object)

In [126]:
apartment_table[apartment_table['District'] == "Есильский район 18"]

,Unnamed: 0,Rooms,Residential complex,City,District,Address,Apartment area,Price,Price/m2,Year,Commissioned/not commissioned,Housing class,Material
447,447,1-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,95.84 м²,60 379 200,630 000,2025,Не сдан,NaN,Unknown
448,448,1-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,89.12 м²,57 036 800,640 000,2025,Не сдан,NaN,Unknown
450,450,2-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,41.3 м²,17 015 600,412 000,2025,Не сдан,Эконом,Unknown
451,451,2-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,41.3 м²,17 015 600,412 000,2025,Не сдан,Эконом,Unknown
452,452,2-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,62.97 м²,23 928 600,380 000,2025,Не сдан,Эконом,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,612,2-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,52.61 м²,20 623 120,392 000,2025,Не сдан,Эконом,Unknown
613,613,3-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,85.12 м²,29 451 520,346 000,2025,Не сдан,Эконом,Unknown
614,614,3-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,84.38 м²,29 617 380,351 000,2025,Не сдан,Эконом,Unknown
615,615,3-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,84.35 м²,36 186 150,429 000,2025,Не сдан,Эконом,Unknown
616,616,2-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,52.58 м²,20 611 360,392 000,2025,Не сдан,Эконом,Unknown

In [127]:
apartment_table[apartment_table['District'] == "Есильский район 15"]

,Unnamed: 0,Rooms,Residential complex,City,District,Address,Apartment area,Price,Price/m2,Year,Commissioned/not commissioned,Housing class,Material
878,878,1-комнатной,Jetisu. Kerbez,г. Астана,Есильский район 15,"ул. Е-509, 7",31.98 м²,15 798 120,494 000,2025,Не сдан,Эконом,Unknown

In [128]:
apartment_table.loc[apartment_table['District'] == "Есильский район 18", 'Address'] = "ул. Толе би 18"
apartment_table.loc[apartment_table['District'] == "Есильский район 15", 'Address'] = "ул. Е-509, 7"

In [129]:
apartment_table[apartment_table['District'] == "Есильский район 18"]

,Unnamed: 0,Rooms,Residential complex,City,District,Address,Apartment area,Price,Price/m2,Year,Commissioned/not commissioned,Housing class,Material
447,447,1-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,95.84 м²,60 379 200,630 000,2025,Не сдан,NaN,Unknown
448,448,1-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,89.12 м²,57 036 800,640 000,2025,Не сдан,NaN,Unknown
450,450,2-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,41.3 м²,17 015 600,412 000,2025,Не сдан,Эконом,Unknown
451,451,2-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,41.3 м²,17 015 600,412 000,2025,Не сдан,Эконом,Unknown
452,452,2-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,62.97 м²,23 928 600,380 000,2025,Не сдан,Эконом,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,612,2-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,52.61 м²,20 623 120,392 000,2025,Не сдан,Эконом,Unknown
613,613,3-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,85.12 м²,29 451 520,346 000,2025,Не сдан,Эконом,Unknown
614,614,3-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,84.38 м²,29 617 380,351 000,2025,Не сдан,Эконом,Unknown
615,615,3-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,84.35 м²,36 186 150,429 000,2025,Не сдан,Эконом,Unknown
616,616,2-комнатной,AruPark,г. Астана,Есильский район 18,ул. Толе би 18,52.58 м²,20 611 360,392 000,2025,Не сдан,Эконом,Unknown

In [130]:
apartment_table[apartment_table['District'] == "Есильский район 15"]

,Unnamed: 0,Rooms,Residential complex,City,District,Address,Apartment area,Price,Price/m2,Year,Commissioned/not commissioned,Housing class,Material
878,878,1-комнатной,Jetisu. Kerbez,г. Астана,Есильский район 15,"ул. Е-509, 7",31.98 м²,15 798 120,494 000,2025,Не сдан,Эконом,Unknown

In [131]:
apartment_table

,Unnamed: 0,Rooms,Residential complex,City,District,Address,Apartment area,Price,Price/m2,Year,Commissioned/not commissioned,Housing class,Material
0,0,4-комнатной,Anar,г. Астана,Есильский район,ул. Орынбор 13,127 м²,75 000 000,590 551,2023,Сдан,Комфорт,Кирпичные
1,1,2-комнатной,Garden View,г. Астана,Есильский район,ул. Бухар жырау 26 стр,47.68 м²,43 950 000,921 770,2024,Не сдан,Бизнес+,Монолитные
2,2,3-комнатной,Самрук Towers,г. Астана,Нура район,ул. Кайыма Мухамедханова 17,86 м²,38 000 000,441 860,2018,Сдан,Эконом,Монолитные
3,3,1-комнатной,GreenLine.Headliner,г. Астана,Есильский район,ул. Толе би 50,45 м²,37 500 000,833 333,2022,Не сдан,Бизнес,Unknown
4,4,2-комнатной,GreenLine.Flora,г. Астана,Есильский район,ул. Е 900 4,50.1 м²,35 500 000,708 583,2024,Не сдан,Бизнес,Монолитные
...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,895,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,62.96 м²,27 576 480,438 000,2025,Не сдан,Эконом,Unknown
896,896,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,62.96 м²,27 576 480,438 000,2025,Не сдан,Эконом,Unknown
897,897,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,59.43 м²,29 358 420,494 000,2025,Не сдан,Эконом,Unknown
898,898,1-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,34.38 м²,18 633 960,542 000,2025,Не сдан,Эконом,Unknown
899,899,3-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,84.35 м²,35 427 000,420 000,2025,Не сдан,Эконом,Unknown

In [132]:
apartment_table[apartment_table['Address'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, Rooms, Residential complex, City, District, Address, Apartment area, Price, Price/m2, Year, Commissioned/not commissioned, Housing class, Material]
Index: []

In [133]:
unknown_rows = apartment_table[apartment_table['Address'] == 'Unknown']
unknown_rows

,Unnamed: 0,Rooms,Residential complex,City,District,Address,Apartment area,Price,Price/m2,Year,Commissioned/not commissioned,Housing class,Material
5,5,4-комнатной,Abyroi,г. Астана,ул. Т. Рыскулова,Unknown,117.75 м²,61 583 250,523 000,2026,Не сдан,Комфорт,Unknown
6,6,4-комнатной,Abyroi,г. Астана,ул. Т. Рыскулова,Unknown,121.8 м²,65 650 200,539 000,2026,Не сдан,Комфорт,Unknown
7,7,4-комнатной,Abyroi,г. Астана,ул. Т. Рыскулова,Unknown,121.81 м²,67 360 930,553 000,2026,Не сдан,Комфорт,Unknown
8,8,4-комнатной,Abyroi,г. Астана,ул. Т. Рыскулова,Unknown,115.25 м²,62 004 500,538 000,2026,Не сдан,Комфорт,Unknown
9,9,4-комнатной,Abyroi,г. Астана,ул. Т. Рыскулова,Unknown,121.81 м²,67 360 930,553 000,2026,Не сдан,Комфорт,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,895,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,62.96 м²,27 576 480,438 000,2025,Не сдан,Эконом,Unknown
896,896,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,62.96 м²,27 576 480,438 000,2025,Не сдан,Эконом,Unknown
897,897,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,59.43 м²,29 358 420,494 000,2025,Не сдан,Эконом,Unknown
898,898,1-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,34.38 м²,18 633 960,542 000,2025,Не сдан,Эконом,Unknown
899,899,3-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,84.35 м²,35 427 000,420 000,2025,Не сдан,Эконом,Unknown

In [134]:
apartment_table[apartment_table['District'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, Rooms, Residential complex, City, District, Address, Apartment area, Price, Price/m2, Year, Commissioned/not commissioned, Housing class, Material]
Index: []

In [135]:
districts_with_nan_address = apartment_table[apartment_table['District'].isna()]['Residential complex'].unique()
districts_with_nan_address

array([], dtype=object)

In [81]:
apartment_table.loc[apartment_table['Residential complex'] == "Anar", 'District'] = "Есильский район"
apartment_table.loc[apartment_table['Residential complex'] == "Garden View", 'District'] = "Есильский район"
apartment_table.loc[apartment_table['Residential complex'] == "Самрук Towers", 'District'] = "Нура район"
apartment_table.loc[apartment_table['Residential complex'] == "GreenLine.Headliner", 'District'] = "Есильский район"
apartment_table.loc[apartment_table['Residential complex'] == "GreenLine.Flora", 'District'] = "Есильский район"
apartment_table.loc[apartment_table['Residential complex'] == "Izet", 'District'] = "Есильский район"
apartment_table.loc[apartment_table['Residential complex'] == "Besterek", 'District'] = "Есильский район"
apartment_table.loc[apartment_table['Residential complex'] == "MoD. Standard", 'District'] = "Есильский район"
apartment_table.loc[apartment_table['Residential complex'] == "MoD. Comfort", 'District'] = "Есильский район"
apartment_table.loc[apartment_table['Residential complex'] == "Aisar", 'District'] = "Есильский район"
apartment_table.loc[apartment_table['Residential complex'] == "Capital Park. Emotions", 'District'] = "Есильский район"
apartment_table

,Unnamed: 0,Rooms,Residential complex,City,District,Address,Apartment area,Price,Price/m2,Year,Commissioned/not commissioned,Housing class,Material
0,0,4-комнатной,Anar,г. Астана,Есильский район,ул. Орынбор 13,127 м²,75 000 000,590 551,2023,Сдан,Комфорт,Кирпичные
1,1,2-комнатной,Garden View,г. Астана,Есильский район,ул. Бухар жырау 26 стр,47.68 м²,43 950 000,921 770,2024,Не сдан,Бизнес+,Монолитные
2,2,3-комнатной,Самрук Towers,г. Астана,Нура район,ул. Кайыма Мухамедханова 17,86 м²,38 000 000,441 860,2018,Сдан,Эконом,Монолитные
3,3,1-комнатной,GreenLine.Headliner,г. Астана,Есильский район,ул. Толе би 50,45 м²,37 500 000,833 333,2022,Не сдан,Бизнес,NaN
4,4,2-комнатной,GreenLine.Flora,г. Астана,Есильский район,ул. Е 900 4,50.1 м²,35 500 000,708 583,2024,Не сдан,Бизнес,Монолитные
...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,895,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,62.96 м²,27 576 480,438 000,2025,Не сдан,Эконом,NaN
896,896,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,62.96 м²,27 576 480,438 000,2025,Не сдан,Эконом,NaN
897,897,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,59.43 м²,29 358 420,494 000,2025,Не сдан,Эконом,NaN
898,898,1-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,34.38 м²,18 633 960,542 000,2025,Не сдан,Эконом,NaN
899,899,3-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,84.35 м²,35 427 000,420 000,2025,Не сдан,Эконом,NaN

In [138]:
#remove rows where Residential complex is NaN
apartment_table = apartment_table[~apartment_table['Residential complex'].isna()]
print(apartment_table['Residential complex'].isna().sum())

0

In [137]:
apartment_table.loc[apartment_table['Material'].isna(), 'Material'] = 'Unknown'
apartment_table

,Unnamed: 0,Rooms,Residential complex,City,District,Address,Apartment area,Price,Price/m2,Year,Commissioned/not commissioned,Housing class,Material
0,0,4-комнатной,Anar,г. Астана,Есильский район,ул. Орынбор 13,127 м²,75 000 000,590 551,2023,Сдан,Комфорт,Кирпичные
1,1,2-комнатной,Garden View,г. Астана,Есильский район,ул. Бухар жырау 26 стр,47.68 м²,43 950 000,921 770,2024,Не сдан,Бизнес+,Монолитные
2,2,3-комнатной,Самрук Towers,г. Астана,Нура район,ул. Кайыма Мухамедханова 17,86 м²,38 000 000,441 860,2018,Сдан,Эконом,Монолитные
3,3,1-комнатной,GreenLine.Headliner,г. Астана,Есильский район,ул. Толе би 50,45 м²,37 500 000,833 333,2022,Не сдан,Бизнес,Unknown
4,4,2-комнатной,GreenLine.Flora,г. Астана,Есильский район,ул. Е 900 4,50.1 м²,35 500 000,708 583,2024,Не сдан,Бизнес,Монолитные
...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,895,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,62.96 м²,27 576 480,438 000,2025,Не сдан,Эконом,Unknown
896,896,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,62.96 м²,27 576 480,438 000,2025,Не сдан,Эконом,Unknown
897,897,2-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,59.43 м²,29 358 420,494 000,2025,Не сдан,Эконом,Unknown
898,898,1-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,34.38 м²,18 633 960,542 000,2025,Не сдан,Эконом,Unknown
899,899,3-комнатной,AQJUREK,г. Астана,ул. Улы дала,Unknown,84.35 м²,35 427 000,420 000,2025,Не сдан,Эконом,Unknown

In [139]:
#сalculate the most common 'Housing class' for each 'Rooms' group
modes = apartment_table.groupby('Rooms')['Housing class'].transform(lambda x: x.mode()[0] if not x.mode().empty else None)
#fill missing 'Housing class' values with the mode of their corresponding 'Rooms'
apartment_table.loc[apartment_table['Housing class'].isna(), 'Housing class'] = modes

apartment_table.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 898 entries, 0 to 899
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     898 non-null    int64
 1   Rooms                          898 non-null    object
 2   Residential complex            898 non-null    object
 3   City                           898 non-null    object
 4   District                       898 non-null    object
 5   Address                        898 non-null    object
 6   Apartment area                 898 non-null    object
 7   Price                          898 non-null    object
 8   Price/m2                       898 non-null    object
 9   Year                           898 non-null    int64
 10  Commissioned/not commissioned  898 non-null    object
 11  Housing class                  898 non-null    object
 12  Material                       898 non-null    object
dtypes: int64(2), object(11)
memory usage: 98.2+ KB

In [140]:
apartment_table.to_csv('apartment_cleaned.csv')